# Increase memory available to gradle
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# https://fabricmc.net/develop/
minecraft_version=26.3
loader_version=0.19.5

# Mod Properties
mod_version=5.2.0
maven_group=io.grayray75.mods
archives_base_name=fpsdisplay

# Dependencies
fabric_version=0.160.5+26.3
modmenu_version=21.0.0-beta.1
cloth_config_version=26.3.158
yacl_config_version=3.9.6+26.3
