# Increase memory available to gradle
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.5

# Mod Properties
mod_version=5.1.0
maven_group=io.grayray75.mods
archives_base_name=fpsdisplay

# Dependencies
fabric_version=0.160.0+26.2
modmenu_version=20.0.2
cloth_config_version=26.2.155
yacl_config_version=3.9.6+26.2
