# Increase memory available to gradle
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=5.0.1
maven_group=io.grayray75.mods
archives_base_name=fpsdisplay

# Dependencies
fabric_version=0.152.1+26.2
modmenu_version=20.0.0-beta.2
cloth_config_version=26.1.154
yacl_config_version=3.9.4+26.2
